# This is a basic workflow to help you get started with Actions
name: Issue assignment

# Controls when the workflow will run
on:
  # Triggers the workflow on opened issues
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "auto-assign"
  auto-assign:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1.0.3
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: fer-dev-mx
